name: C-Runner

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install GCC
      run: sudo apt-get install gcc

    - name: Build and Run C Code
      run: |
        gcc -o my_program mystic_ov_26.c -lm  # Note: -lm flag to link with math library
        ./my_program
